services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - CERTS_DIR=${CERTS_DIR}
    command: >
      bash -c '
        /tmp/create-certs.sh
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: 
      - ./create-certs.sh:/tmp/create-certs.sh
      - ./instances.yml:/tmp/instances.yml 
      - ./certs:$CERTS_DIR

#volumes: {"elastic_certs"}
